version: '3'
services:
  file-converter-worker:
    build: ./../appNube_Miso
    environment:
      - DATABASE_URI=mysql://root:LoA227bC4_Q_FMB@35.247.106.203:3306/file-converter
      - GCP_BUCKET_NAME=file-converter-bucket
      - GCP_PROJECT_ID=miso-nube
      - GCP_SUBSCRIPTION_NAME=file-converter-sub
      - GCP_TOPIC_NAME=file-converter
    command:
      - python
      - worker.py
    volumes:
      - ./files:/app/files
    ports:
      - "5000:5000"
  file-converter-service:
    build: ./../appNube_Miso
    environment:
      - DATABASE_URI=mysql://root:LoA227bC4_Q_FMB@35.247.106.203:3306/file-converter
      - GCP_BUCKET_NAME=file-converter-bucket
      - GCP_PROJECT_ID=miso-nube
      - GCP_SUBSCRIPTION_NAME=file-converter-sub
      - GCP_TOPIC_NAME=file-converter
    command:
      - python
      - service.py
    volumes:
      - ./files:/app/files
    ports:
      - "5000:5000"
